### ISSUE TITLE
Drawer box on the right not accessible

### ISSUE THREAD

**Issue by frieder** [KebirYacine/xwiki-thatha-color-theme#1]
Hi

I've tried to use this theme on 8.0 (I know it's only valid until 7.0 but it's the best theme I've found so far) and I've found one issue when the panel on the right cannot be accessed anymore because it gets overlayed as can be seen at [0]. Are you planning to release another version that is compatible with 8.0?

Cheers
Frieder

[0] http://imgur.com/a/DYYzF

**Comment by KebirYacine** [comment]
Hi Frieder
thank you for your contribution, yes i will correct the bug and make a new release next week.
cordially

**Comment by frieder** [comment]
That's great news, thx

**Comment by KebirYacine** [comment]
A new release is available
